server:
  port: 7070

spring:
  springdoc:
    api-docs:
      path: /api-docs
  cloud:
    gateway:
      discovery:
        locator:
          #使用小写服务名，默认是大写
          lower-case-service-id: true
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chatService/**
          filters:
            - StripPrefix=1
        - id: manage-service
          uri: lb://manage-service
          predicates:
            - Path=/manageService/**
          filters:
            - StripPrefix=1
        - id: msg-service
          uri: lb://msg-service
          predicates:
            - Path=/msgService/**
          filters:
            - StripPrefix=1
        - id: saToken-service
          uri: lb://saToken-service
          predicates:
            - Path=/saTokenService/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowedMethods:
              - OPTIONS
              - GET
              - POST
              - PUT
            max-age: 3600
# 日志配置
logging:
  level:
    com.example.HfGatewayApplication: DEBUG
