server:
  port: 7090

spring:
  # 数据源配置
  shardingsphere:
    mode:
      #  运行模式类型。可选配置：Standalone、Cluster
      type: Standalone
      #  repository (?): # 久化仓库配置
    #      repository:
    #        type: JDBC
    # 数据源配置
    datasource:
      # 你的主从数据源配置
      names: hf_master,hf_slave
      # 主数据库配置
      hf_master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${database.master.url}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: ${database.master.user}
        password: ${database.master.password}
        # 从数据库配置
      hf_slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${database.slave.url}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: ${database.slave.user}
        password: ${database.slave.password}
    # 规则配置
    rules:
      #      # 主从同步
      #      name: readwrite_ds
      #      masterDataSourceName: t_master
      #      slaveDataSourceNames: [t_slave]
      #      loadBalanceAlgorithmName: round_robin
      #      props:
      #        sync-wait-timeout-millis: 5000  # 同步等待超时时间
      # 禁用shardingsphere id生成
      tables:
        t_user:
          keyGenerateStrategy: # 禁用分布式 ID 生成器
            column: id
            keyGenerator:
              type: NONE
      # 声明使用读写分离
      readwrite-splitting:
        # 读写分离的数据源配置
        data-sources:
          readwrite_ds:
            # 静态策略
            static-strategy:
              write-data-source-name: hf_master
              read-data-source-names:
                - hf_slave
            # 负载均衡器名称
            load-balancer-name: round_robin
        #            props:
        #              sync-wait-timeout-millis: 5000  # 同步等待超时时间
        #              max-connections-size-per-query: 1  # 每个查询的最大连接数
        # 负载均衡器配置
        load-balancers:
          # 轮询负载均衡器
          round_robin:
            # 类型
            type: ROUND_ROBIN
    props:
      # 开启 SQL 日志打印（必填）
      sql-show: true
      # 可选，格式化 SQL 输出（美观易读）
      sql-format: true
      executor-size: 16  # 工作线程数
      max-connections-size-per-query: 1
      transaction-isolation-level: REPEATABLE_READ

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.example.**.domain
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
